# NeoVimのプラグインマネージャー。これないとやばい
[[plugins]]
repo = 'Shougo/dein.vim'

# Lint エンジン。サイドバーの矢印とコメントでチェックしてくれる
[[plugins]]
repo = 'w0rp/ale'

# LSP. COC便利なので利用
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = '''
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? coc#_select_confirm() :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)

  let g:coc_global_extensions = [
  \ 'coc-solargraph',
  \ 'coc-tsserver',
  \ 'coc-prettier',
  \ 'coc-eslint',
  \ 'coc-git',
  \ 'coc-markdownlint',
  \ 'coc-pairs',
  \ 'coc-prettier',
  \ 'coc-yaml',
  \ 'coc-java',
  \ 'coc-css',
  \ 'coc-html',
  \ 'coc-sql',
  \ 'coc-pyright',
  \ 'coc-go',
  \ 'coc-json'
  \ ]
'''
# inoremap <silent><expr> <tab> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<cr>"
# inoremap <silent><expr> <TAB>
  #       \ pumvisible() ? "\<C-n>" :
  #       \ <SID>check_back_space() ? "\<TAB>" :
  #       \ coc#refresh()
  # inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
  # inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
# ファイル検索。regexからファイル名までいけるので必須
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nnoremap fb :Buffers<CR>
  nnoremap fg :Rg<CR>
  nnoremap ff :Files<CR>
  nnoremap fc :Commits<CR>
  set rtp+=/usr/local/opt/fzf
'''
  # set rtp+=~/.fzf

# ファイラ. プロジェクトのファイル一覧の操作が可能
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
  nnoremap <C-e> :NERDTreeToggle<CR>
'''

# 作業中のブランチやファイル名、を画面の下部と上部に表示
[[plugins]]
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
    let g:airline_theme = 'wombat'
    let g:airline#extensions#hunks#enabled = 0
    let g:airline#extensions#branch#enabled = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
'''

# 差分を左に-と+で教えてくれる
[[plugins]]
repo = "airblade/vim-gitgutter"

# Gitに関するコマンドを使うことが可能。超便利
[[plugins]]
repo = "tpope/vim-fugitive"

# ファイルに応じてコメントを可能にしてくれる
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    vnoremap ? :'<,'>TComment<CR>
'''

# 括弧に色をつけてわかりやすくしてくれる。だいじ
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

# solarizedのカラースキーマ
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# 簡単に括弧やクオテーションで囲める。超重要
[[plugins]]
repo = 'tpope/vim-surround'

# Goのデバッガ。あんまり使ってないかも
[[plugins]]
repo = 'sebdah/vim-delve'

# コード整形。使える言語限られているので、利用のタイミングは割と限定的
[[plugins]]
repo  = 'prettier/vim-prettier'
build = 'npm install'

# インデントを見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# カッコやクオテーションの自動追加
[[plugins]]
repo = 'jiangmiao/auto-pairs'

